using System;
using System.Data.Linq;
using System.Data.linq.mapping;

namespace AngularProjectOne.Models
{
[Table(Name = "Contact")]
public class Contact
{
	private string customerID;
	private string email;
    private string phone;
	private EntityRef<Address> address;
	private EntityRef<Customer> customer;
	public Contact()
	{
		Email = "";
		Phone = "";

	}

	 [Column(Storage = "cusomerID", DbType = "Int NOT NULL IDENTITY", 
		IsPrimaryKey = true, IsDbGenerated = true)]
	public int customerID // No set, auto generated by the Database.
	{
		get
		{
			return this.customerID;
		}
		
	}

	[Column(storage = "phone")]
	public string Phone
	{
		get
		{
			return this.phone;
		}
		set
		{
			this.phone = value;
		}
	}
	
	[Column(storage = "email")] 
	public string Email
	{
		get
		{
			return this.email;
		}
		set
		{
			this.email = value;
		}
		
	}
	[Asssociation(Storage = "customer", ThisKey = "CustomerID")] // access to customer and address classes
	public Customer Customer
	{
		get { return this.customer.Entity; }
		set { this.customer.Entity = value;  }
	}
	[Asssociation(Storage = "address", ThisKey = "CustomerID")] 
	public Customer Customer
	{
		get { return this.address.Entity; }
		set { this.address.Entity = value; }
	}
}
}